### PR TITLE
java doc params use api params to render. fix include java full content

### LINKED ISSUE #322: Switch Include javadoc parameters plugin to use API Params component
Javadoc include params plugin was developed before adding api params component. 
We need to switch java params to use it instead of custom template. 
Additionally add support for style and not just text when extracting params description.

### PR DESCRIPTION
**Pull request by MykolaGolubyev**
Additionally separated java.md into java.md and java-doc.md.

image

closes #322

### CODE REVIEW

File: znai-java/src/main/java/com/twosigma/znai/java/extensions/JavaIncludePlugin.java [hunk 1]
```diff
@@ -76,7 +76,7 @@ public JavaIncludeResult process(JavaCode javaCode) {
     }
 
     private String extractContent(JavaCode javaCode) {
-        if (entry == null && entries == null) {
+        if (entry == null && entries.isEmpty()) {
```
Comment (byc1234) [inline znai-java/src/main/java/com/twosigma/znai/java/extensions/JavaIncludePlugin.java]: Redundant.
JavaPluginIncludeBase.process() already checks the condition.

Comment (MykolaGolubyev) [reply znai-java/src/main/java/com/twosigma/znai/java/extensions/JavaIncludePlugin.java]: This condition is slightly different. It says if no entry or entries is defined use the entire java file to render and not a piece of a method. It was buggy for the last 2 months and was rendering nothing as this `entires` was changed to be an empty array instead of null. There was no test for this case, hence I added it now.

Comment (byc1234) [reply znai-java/src/main/java/com/twosigma/znai/java/extensions/JavaIncludePlugin.java]: Got you.
