### PR TITLE
revamp TOC update event during preview. toc items presence validation.

### LINKED ISSUE #76: Provide better error message for toc pointing to nonexistent MD
```
Exception in thread "main" java.lang.RuntimeException: error during parsing of <chapter-name/page-name>:/path/docs/mdoc/chapter-name/page-name.md doesn't exist
        at com.twosigma.documentation.website.WebSite.parseMarkupAndUpdateTocItem(WebSite.java:302)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
        at com.twosigma.documentation.website.WebSite.parseMarkups(WebSite.java:261)
        at com.twosigma.documentation.website.WebSite.generate(WebSite.java:134)
        at com.twosigma.documentation.website.WebSite$Configuration.deployTo(WebSite.java:570)
        at com.twosigma.documentation.cli.DocumentationCliApp.generateDocs(DocumentationCliApp.java:110)
        at com.twosigma.documentation.cli.DocumentationCliApp.start(DocumentationCliApp.java:65)
        at com.twosigma.documentation.cli.DocumentationCliApp.main(DocumentationCliApp.java:40)
Caused by: java.lang.RuntimeException: /path/docs/mdoc/chapter-name/page-name.md doesn't exist
        at com.twosigma.utils.FileUtils.fileTextContent(FileUtils.java:33)
        at com.twosigma.documentation.website.WebSite.parseMarkupAndUpdateTocItem(WebSite.java:285)
        ... 8 more
```

Pretty sure this was because I renamed the page and forgot to update toc.

### PR DESCRIPTION
**Pull request by MykolaGolubyev**
Also closes #76

### CODE REVIEW

File: znai-reactjs/src/doc-elements/Documentation.js [hunk 1]
```diff
@@ -487,24 +487,23 @@ export class Documentation extends Component {
...
         this.navigateToPageAndDisplayChange(pageProps, updatePagesReference)
     }
 
     // one of the files referred from a markup or multiple markups was changed
-    // we need to update multiple pages at once and either refresh current view (if one of the changed pages is it)
+    // we need to update multiple pages at once and either refresh current view (if one of the changed pages is current page)
     // or navigate to the first modified page
     //
     onMultiplePagesUpdate(listOfPageProps) {
         const updatePagesReference = () => this.getAllPagesPromise().then((allPages) => {
```
Comment (byc1234) [inline znai-reactjs/src/doc-elements/Documentation.js]: Can you move this local method to class method, so you can reuse it within `onPageUpdate`, too?
